name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  tests:
    env:
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.0
          bundler-cache: true

      - name: Install npm dependencies
        run: npm install

      - name: Build site
        run: bundle exec jekyll build --verbose --trace
        env:
          JEKYLL_ENV: local

      - name: Run tests
        run: bundle exec htmlproofer _site --disable-external --url-ignore "#top" --allow-hash-href --checks-to-ignore ScriptCheck
